[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
itertools = "0.11.0"
lazy_static = "1.4.0"
pathfinding = "4.3.0"
rand = "0.8.5"
regex = "1.8.4"
